// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const AUTH_STORAGE_KEY = import.meta.env.VITE_SUPABASE_AUTH_STORAGE_KEY || 'zcraft-auth';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SSR-safe deep proxy: returns chainable no-ops for any access path during SSR.
function createSSRMock(): any {
  const handler: ProxyHandler<any> = {
    get(_target, prop) {
      if (prop === 'then') return undefined; // not a thenable
      if (prop === Symbol.toPrimitive) return () => '';
      // Common terminal methods that should resolve with empty data
      if (prop === 'subscribe') {
        return () => ({ data: { subscription: { unsubscribe: () => {} } } });
      }
      // Default: return a callable proxy that also resolves like a query
      const fn: any = (..._args: any[]) => createSSRMock();
      return new Proxy(fn, handler);
    },
    apply() {
      return createSSRMock();
    },
  };
  const base: any = function noop() { return createSSRMock(); };
  // Make the proxy itself awaitable to `{ data, error }`-shaped results
  base.then = (resolve: any) => resolve({ data: null, error: null });
  return new Proxy(base, handler);
}

export const supabase: SupabaseClient<Database> = (typeof window === 'undefined'
  ? createSSRMock()
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        storageKey: AUTH_STORAGE_KEY,
        storage: window.localStorage,
      },
    })) as SupabaseClient<Database>;

